module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    COUPON_COLLECTION:'coupon',
    OFFER_COLLECTION:'offer',
    WALLET_COLLECTION:'wallet'
}